url: https://cadquery.github.io

title: CadQuery
description: Create parametric CAD models with Python

remote_theme: pages-themes/minimal@v0.2.0

logo: /assets/images/cadquery_logo_dark.svg

github:
  repository_url: https://github.com/cadquery/cadquery
  repository_name: cadquery
  repository_nwo: CadQuery/cadquery
  owner_name: the CadQuery organization
  owner_url: https://github.com/cadquery

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
